FROM ruby:3.2.5-slim

RUN apt-get update -qq && apt-get install -y build-essential git libpq-dev

WORKDIR /elovation
COPY Gemfile /elovation/Gemfile
COPY Gemfile.lock /elovation/Gemfile.lock
RUN bundle install

ENTRYPOINT ["./bin/docker-entrypoint"]
EXPOSE 3000

# Configure the main process to run when running the image
CMD ["./bin/rails", "server", "-b", "0.0.0.0"]
