services:
  db:
    #    ports:
    #  - 5432:5432
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && ./bin/dev"
    environment:
      - PGHOST=db
    tty: true
    volumes:
      - .:/elovation
    ports:
      - "4321:3000"
    depends_on:
      - db
